[package]
name = "actix-git"
version = "0.1.0"
authors = ["Dan Thompson <dthompson@fitbit.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "1.0.0-alpha.4"
env_logger = "0.6"
juniper = "0.9.2"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
git2 = "0.8"
